# Day 5: Exercises

## Exercise 1: Navigation
Load `4xp1.pdb` and print all atoms in the structure.

In [2]:
from Bio.PDB import *
parser = PDBParser()
structure = parser.get_structure( "4XP1","4xp1.pdb")

for model in structure:
    for chain in model:
        for residue in chain:
            for atom in residue:
                print(atom)
                
#or

atoms = structure.get_atoms()
for atom in atoms:
    print(atom)


/home/matze/anaconda3/lib/python3.6/site-packages/Bio/PDB/StructureBuilder.py:90: PDBConstructionWarning: WARNING: Chain A is discontinuous at line 8222.
  PDBConstructionWarning)
/home/matze/anaconda3/lib/python3.6/site-packages/Bio/PDB/StructureBuilder.py:90: PDBConstructionWarning: WARNING: Chain L is discontinuous at line 8403.
  PDBConstructionWarning)
/home/matze/anaconda3/lib/python3.6/site-packages/Bio/PDB/StructureBuilder.py:90: PDBConstructionWarning: WARNING: Chain A is discontinuous at line 8404.
  PDBConstructionWarning)
/home/matze/anaconda3/lib/python3.6/site-packages/Bio/PDB/StructureBuilder.py:90: PDBConstructionWarning: WARNING: Chain L is discontinuous at line 8419.
  PDBConstructionWarning)
/home/matze/anaconda3/lib/python3.6/site-packages/Bio/PDB/StructureBuilder.py:90: PDBConstructionWarning: WARNING: Chain H is discontinuous at line 8422.
  PDBConstructionWarning)


<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom OD1>
<Atom OD2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD>
<Atom OE1>
<Atom OE2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD>
<Atom NE>
<Atom CZ>
<Atom NH1>
<Atom NH2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD>
<Atom OE1>
<Atom OE2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom OG1>
<Atom CG2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD1>
<Atom CD2>
<Atom NE1>
<Atom CE2>
<Atom CE3>
<Atom CZ2>
<Atom CZ3>
<Atom CH2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom OG>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD>
<Atom CE>
<Atom NZ>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG1>
<Atom CG2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom OD1>
<Atom OD2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD1>
<Atom CD2>
<Atom CE1>
<

<Atom CG2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom OD1>
<Atom OD2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom OG1>
<Atom CG2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD>
<Atom OE1>
<Atom NE2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG1>
<Atom CG2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD1>
<Atom CD2>
<Atom CE1>
<Atom CE2>
<Atom CZ>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD1>
<Atom CD2>
<Atom CE1>
<Atom CE2>
<Atom CZ>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom OG>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD1>
<Atom CD2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD1>
<Atom CD2>
<Atom CE1>


<Atom OD2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG1>
<Atom CG2>
<Atom CD1>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD>
<Atom NE>
<Atom CZ>
<Atom NH1>
<Atom NH2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom OD1>
<Atom OD2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom SD>
<Atom CE>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG1>
<Atom CG2>
<Atom CD1>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD1>
<Atom CD2>
<Atom CE1>
<Atom CE2>
<Atom CZ>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD>
<Atom NE>
<Atom CZ>
<Atom NH1>
<Atom NH2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD1>
<Atom CD2>
<Atom CE1>
<Atom CE2>
<Atom CZ>
<Atom OH>
<Atom N>
<Atom 

<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD>
<Atom CE>
<Atom NZ>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom OD1>
<Atom OD2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG1>
<Atom CG2>
<Atom CD1>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom OD1>
<Atom ND2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG1>
<Atom CG2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD>
<Atom CE>
<Atom NZ>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD1>
<Atom CD2>
<Atom NE1>
<Atom CE2>
<Atom CE3>
<Atom CZ2>
<Atom CZ3>
<Atom CH2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD>
<Atom CE>
<Atom NZ>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG1>
<Atom CG2>
<Atom CD1>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom OG>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD>

<Atom O>
<Atom CB>
<Atom OG1>
<Atom CG2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD1>
<Atom CD2>
<Atom NE1>
<Atom CE2>
<Atom CE3>
<Atom CZ2>
<Atom CZ3>
<Atom CH2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom OG>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD>
<Atom OE1>
<Atom NE2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom OG>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG1>
<Atom CG2>
<Atom CD1>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom OG1>
<Atom CG2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom SG>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom OD1>
<Atom ND2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG1>
<Atom CG2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom ND1>
<Atom CD2>
<Atom CE1>
<Atom NE2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom

<Atom CB>
<Atom OG>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD1>
<Atom CD2>
<Atom CE1>
<Atom CE2>
<Atom CZ>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD1>
<Atom CD2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG1>
<Atom CG2>
<Atom CD1>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD>
<Atom OE1>
<Atom NE2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD1>
<Atom CD2>
<Atom CE1>
<Atom CE2>
<Atom CZ>
<Atom OH>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD1>
<Atom CD2>
<Atom CE1>
<Atom CE2>
<Atom CZ>
<Atom OH>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD1>
<Atom CD2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom OG1>
<Atom CG2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom OD1>
<Atom ND2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<

<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD1>
<Atom CD2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom OG1>
<Atom CG2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD1>
<Atom CD2>
<Atom CE1>
<Atom CE2>
<Atom CZ>
<Atom OH>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom OD1>
<Atom OD2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD1>
<Atom CD2>
<Atom CE1>
<Atom CE2>
<Atom CZ>
<Atom OH>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG1>
<Atom CG2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD1>
<Atom CD2>
<Atom CE1>
<Atom CE2>
<Atom CZ>
<Atom OH>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom OG>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD1>
<Atom CD2>
<Atom NE1>
<Atom CE2>
<Atom CE3>
<Atom CZ2>
<Atom CZ3>
<Atom CH2>
<Atom N>
<Atom CA>
<Atom 

<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD>
<Atom CE>
<Atom NZ>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom OD1>
<Atom OD2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD1>
<Atom CD2>
<Atom CE1>
<Atom CE2>
<Atom CZ>
<Atom OH>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD>
<Atom OE1>
<Atom OE2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom ND1>
<Atom CD2>
<Atom CE1>
<Atom NE2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom OD1>
<Atom ND2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom OG>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD1>
<Atom CD2>
<Atom CE1>
<Atom CE2>
<Atom CZ>
<Atom OH>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom OG1>
<Atom CG2>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom SG>
<Atom N>
<Atom CA>
<Atom C>
<Atom O>
<Atom CB>
<Atom CG>
<Atom CD

Print all residues in chain A:

In [3]:
chain_L = model["L"]
for residue in chain_L:
    print(residue)

<Residue GLU het=  resseq=1 icode= >
<Residue ASN het=  resseq=2 icode= >
<Residue VAL het=  resseq=3 icode= >
<Residue LEU het=  resseq=4 icode= >
<Residue THR het=  resseq=5 icode= >
<Residue GLN het=  resseq=6 icode= >
<Residue SER het=  resseq=7 icode= >
<Residue PRO het=  resseq=8 icode= >
<Residue ALA het=  resseq=9 icode= >
<Residue ILE het=  resseq=10 icode= >
<Residue MET het=  resseq=11 icode= >
<Residue SER het=  resseq=12 icode= >
<Residue THR het=  resseq=13 icode= >
<Residue SER het=  resseq=14 icode= >
<Residue PRO het=  resseq=15 icode= >
<Residue GLY het=  resseq=16 icode= >
<Residue GLU het=  resseq=17 icode= >
<Residue LYS het=  resseq=18 icode= >
<Residue VAL het=  resseq=19 icode= >
<Residue THR het=  resseq=20 icode= >
<Residue MET het=  resseq=21 icode= >
<Residue THR het=  resseq=22 icode= >
<Residue CYS het=  resseq=23 icode= >
<Residue ARG het=  resseq=24 icode= >
<Residue ALA het=  resseq=25 icode= >
<Residue SER het=  resseq=26 icode= >
<Residue SER het=  re

Get the list of unique parent residues of some_atoms.

In [4]:
import numpy as np
all_atoms = Selection.unfold_entities(structure,"A")
some_atoms = [all_atoms[np.random.randint(0,len(all_atoms))] for i in range(20)]

In [5]:
parents = Selection.unfold_entities(some_atoms, "R")
print(parents)

[<Residue GLY het=  resseq=541 icode= >, <Residue TYR het=  resseq=87 icode= >, <Residue GLY het=  resseq=560 icode= >, <Residue LYS het=  resseq=441 icode= >, <Residue LEU het=  resseq=86 icode= >, <Residue MET het=  resseq=34 icode= >, <Residue PHE het=  resseq=471 icode= >, <Residue LEU het=  resseq=243 icode= >, <Residue THR het=  resseq=591 icode= >, <Residue VAL het=  resseq=246 icode= >, <Residue ALA het=  resseq=204 icode= >, <Residue GLU het=  resseq=214 icode= >, <Residue MAL het=H_MAL resseq=704 icode= >, <Residue TYR het=  resseq=498 icode= >, <Residue VAL het=  resseq=134 icode= >, <Residue ARG het=  resseq=98 icode= >, <Residue GLN het=  resseq=177 icode= >, <Residue VAL het=  resseq=29 icode= >]


Print all hetro residues in chain A

In [6]:
chain_A = model["A"]
for residue in chain_A:
    residue_id = residue.get_id()
    if residue_id[0][0]=="H":
        print(residue)


<Residue  NA het=H_ NA resseq=701 icode= >
<Residue  NA het=H_ NA resseq=702 icode= >
<Residue  CL het=H_ CL resseq=703 icode= >
<Residue MAL het=H_MAL resseq=704 icode= >
<Residue MAL het=H_MAL resseq=705 icode= >
<Residue NAG het=H_NAG resseq=706 icode= >
<Residue P4G het=H_P4G resseq=707 icode= >
<Residue LDP het=H_LDP resseq=708 icode= >
<Residue EDO het=H_EDO resseq=709 icode= >
<Residue Y01 het=H_Y01 resseq=710 icode= >
<Residue CLR het=H_CLR resseq=711 icode= >


Print the coordinates of all $\alpha$-cabons ("CA") with B-factor greater than 50.

In [7]:
all_residues = Selection.unfold_entities(structure,"R")
for residue in all_residues:
    if residue.has_id("CA"):
        CA = residue["CA"]
        if CA.get_bfactor() > 50:
            print(CA.get_coord())

[-23.479  26.627 -37.609]
[-19.767  27.32  -37.074]
[-18.047  24.999 -34.58 ]
[-14.761  25.767 -32.847]
[-11.498  24.568 -34.35 ]
[ -8.146  23.443 -32.926]
[ -6.089  26.176 -31.295]
[ -3.265  25.004 -33.567]
[ -2.457  22.232 -36.045]
[ -0.137  20.407 -33.635]
[ -2.973  20.223 -31.092]
[ -4.866  17.997 -33.527]
[ -1.92   15.781 -34.462]
[ -0.76   15.295 -30.879]
[ -4.362  14.499 -30.015]
[ -4.495  11.831 -32.745]
[ -0.967  10.561 -32.163]
[ -1.943  10.568 -28.501]
[ -5.16    8.618 -28.952]
[ -3.529   6.019 -31.212]
[ -0.304   5.43  -29.27 ]
[ -1.467   3.24  -26.468]
[ -0.492   0.338 -24.211]
[ -1.178  -2.091 -27.05 ]
[  1.757  -0.439 -28.825]
[  3.961  -1.595 -25.976]
[  2.677  -4.93  -24.689]
[  1.147  -6.496 -27.871]
[  3.33   -5.473 -30.864]
[  6.82   -6.538 -29.741]
[  5.359  -9.822 -28.546]
[  3.765 -10.389 -31.972]
[  7.133  -9.934 -33.673]
[  8.781 -12.33  -31.228]
[  5.915 -14.833 -31.651]
[  5.745 -14.782 -35.477]
[  8.921 -14.776 -37.551]
[ 10.73  -11.959 -35.746]
[ 11.644  -9

[  3.572  44.744 -90.86 ]
[  0.965  47.486 -90.552]
[ -2.054  48.655 -92.504]
[ -3.351  52.242 -92.455]
[ -6.719  53.238 -93.885]
[ -7.771  56.859 -94.385]
[-11.424  57.216 -95.32 ]
[-13.139  60.345 -96.635]
[-16.361  61.236 -98.419]
[ -16.347   60.798 -102.206]
[ -17.031   64.537 -102.17 ]
[-14.021  65.37  -99.979]
[ -11.996   62.888 -102.004]
[ -12.683   64.38  -105.434]
[ -12.202   67.894 -104.032]
[  -8.436   67.514 -103.484]
[  -5.299   67.288 -105.572]
[  -3.053   64.332 -104.551]
[  -2.742   61.861 -101.645]
[  0.373  60.996 -99.648]
[  1.3    58.376 -97.063]
[  4.652  58.656 -95.299]
[  6.29   56.204 -92.907]
[  8.641  57.293 -90.113]
[ 10.817  54.462 -88.82 ]
[ 13.992  54.007 -86.737]
[ 15.725  52.801 -89.907]
[ 15.653  56.057 -91.907]
[ 16.235  59.586 -90.596]
[ 13.969  60.841 -93.389]
[ 10.493  59.352 -93.801]
[  9.707  56.898 -96.613]
[  6.982  58.427 -98.785]
[   4.411   57.154 -101.273]
[   1.926   59.322 -103.178]
[  -0.403   59.42  -106.125]
[  -2.388   62.009 -108.044]

# Exercise 2: Writing a file

Write a file containing only the $\alpha$-carbons.

In [8]:
class alphaSelect(Select):
    def accept_atom(self, atom):
        if atom.get_name() =="CA":
            return True
        else:
            return False
io = PDBIO()
io.set_structure(structure)
io.save("alphas.pdb",alphaSelect())

# Exercise 3: Rotation

Rotate chain H by 90° around the axis defined by its first and last $\alpha$-carbon. Then apply this rotation with atom.set_coord(new_coord). Use nglview to visualize this rotation.

You can do this similar to the Glycin example. Define the axis, take care of the centering and apply the rotation.

Make sure to select the atoms of chain H via the Selection.unfold_entities() method.

In [9]:
structure = parser.get_structure( "4XP1","4xp1.pdb")
model = structure[0]
chain_H = model["H"]

#get axis
atoms = Selection.unfold_entities(chain_H,"A")
dummy=0
for atom in atoms:
    if atom.get_id()=="CA":
        if dummy == 0:
            start = atom.get_vector()
            dummy = 1
        if dummy > 0:
            end =atom.get_vector()
#center at start
axis = end
#create rotmat
rot = rotaxis(np.pi/2,axis)
#apply rotations
for atom in atoms:
    at = atom.get_vector() - start
    at = at.left_multiply(rot)
    at = at + start
    atom.set_coord( np.array([at[i] for i in range(3)]))

import nglview as nv
view = nv.show_biopython(structure)
view.clear_representations()
view.add_ball_and_stick() #view as ball and stick 
view.clear_representations()
#add ribbons
view.add_cartoon('protein')
#add ball and stick for non-rotien
view.add_ball_and_stick('not protein')
view

/home/matze/anaconda3/lib/python3.6/site-packages/Bio/PDB/StructureBuilder.py:90: PDBConstructionWarning: WARNING: Chain A is discontinuous at line 8222.
  PDBConstructionWarning)
/home/matze/anaconda3/lib/python3.6/site-packages/Bio/PDB/StructureBuilder.py:90: PDBConstructionWarning: WARNING: Chain L is discontinuous at line 8403.
  PDBConstructionWarning)
/home/matze/anaconda3/lib/python3.6/site-packages/Bio/PDB/StructureBuilder.py:90: PDBConstructionWarning: WARNING: Chain A is discontinuous at line 8404.
  PDBConstructionWarning)
/home/matze/anaconda3/lib/python3.6/site-packages/Bio/PDB/StructureBuilder.py:90: PDBConstructionWarning: WARNING: Chain L is discontinuous at line 8419.
  PDBConstructionWarning)
/home/matze/anaconda3/lib/python3.6/site-packages/Bio/PDB/StructureBuilder.py:90: PDBConstructionWarning: WARNING: Chain H is discontinuous at line 8422.
  PDBConstructionWarning)


NGLWidget()

# Exercise 4: Identifiers

What do the identifiers of structure, model, chain, residue and atom stand for?

In [10]:
print(structure.get_id())
# String given by the user when reading in the data
print(structure[0].get_id())
# int, number of model in pdb
print(structure[0]["A"].get_id())
# string , name from pdb file
print(structure[0]["L"][('H_ NA', 301, ' ')].get_id())
# three elements, string hetero field, int resseq and string icode
print(structure[0]["L"][100]["CA"].get_id())
#string atomname

4XP1
0
A
('H_ NA', 301, ' ')
CA


# Exercise 5: 

Sumperimpose the two given Alanin residues. Also give the used rotational translational matrices and and the `RMSD`

In [11]:
structure = parser.get_structure( "4XP1","4xp1.pdb")
ala1 = structure[0]["A"][44]
ala2 = structure[0]["H"][131]
#for residue in structure.get_residues():
#    if residue.get_resname() == "ALA":
#        print(residue.get_full_id())

/home/matze/anaconda3/lib/python3.6/site-packages/Bio/PDB/StructureBuilder.py:90: PDBConstructionWarning: WARNING: Chain A is discontinuous at line 8222.
  PDBConstructionWarning)
/home/matze/anaconda3/lib/python3.6/site-packages/Bio/PDB/StructureBuilder.py:90: PDBConstructionWarning: WARNING: Chain L is discontinuous at line 8403.
  PDBConstructionWarning)
/home/matze/anaconda3/lib/python3.6/site-packages/Bio/PDB/StructureBuilder.py:90: PDBConstructionWarning: WARNING: Chain A is discontinuous at line 8404.
  PDBConstructionWarning)
/home/matze/anaconda3/lib/python3.6/site-packages/Bio/PDB/StructureBuilder.py:90: PDBConstructionWarning: WARNING: Chain L is discontinuous at line 8419.
  PDBConstructionWarning)
/home/matze/anaconda3/lib/python3.6/site-packages/Bio/PDB/StructureBuilder.py:90: PDBConstructionWarning: WARNING: Chain H is discontinuous at line 8422.
  PDBConstructionWarning)


In [12]:
ala1_atoms = Selection.unfold_entities(ala1,"A")
ala2_atoms = Selection.unfold_entities(ala2,"A")
# Create the superimposer object
sup = Superimposer()
#
#fixed and moving are lists of atoms
sup.set_atoms(ala1_atoms, ala2_atoms)
print(sup.rotran)
print(sup.rms)
print(ala2_atoms[0].get_coord())
sup.apply(ala2_atoms)
print(ala2_atoms[0].get_coord())

(array([[-0.41215801, -0.89359905,  0.1777822 ],
       [ 0.87516099, -0.33401285,  0.35004093],
       [-0.2534147 ,  0.29986022,  0.91970911]]), array([-74.85244052,  49.53662653,  51.76730318]))
0.6056526469909325
[  -6.076   47.773 -106.356]
[ -3.5869293   7.117405  -30.406982 ]


# Exercise 6: Center of Mass

Write a function that calculates the center of Mass for a chain. 

Hint: atom._assign_atom_mass()

In [13]:
def get_com(chain):
    atoms = chain.get_atoms()
    weighted_sum = np.zeros(3)
    total_mass= 0
    for atom in atoms:
        mass = atom._assign_atom_mass()
        total_mass += mass
        weighted_sum += mass * atom.get_coord()
    return weighted_sum / total_mass

#structure = parser.get_structure( "4XP1","4xp1.pdb")
model = structure[0]
com_A = get_com(model["A"])
print(com_A)
com_L = get_com(model["L"])
print(com_L)
com_H = get_com(model["H"])
print(com_H)

[ -6.7733749    1.10479896 -27.24888572]
[  2.02998963  42.87819494 -81.21002026]
[-13.51674098  33.48050481 -81.93491695]
